TodoNetCore/Models/TaskItem.cs
namespace TodoNetCore.Models
{
    public class TaskItem
    {
        public long TaskId { get; set; }
        public string Subject { get; set; }
        public bool IsComplete { get; set; }
    }
}

TodoNetCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace TodoNetCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TodoNetCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Data.SqlClient;
using TodoNetCore.Models;

namespace TodoNetCore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public TaskItem[] TaskItems { get; private set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            var cn = new SqlConnection();

            var cmd = cn.CreateCommand();
            cmd.CommandText = "SELECT TaskId, Subject, IsComplete FROM TaskItem ORDER BY TaskId DESC";

            try
            {
                cn.ConnectionString = "Data Source=.;Initial Catalog=ToDoDb;User ID=tododb;Password=123456";
                cn.Open();                
                var dr = cmd.ExecuteReader();
                var taskItems = new List<TaskItem>();

                while (dr.Read())
                {
                    taskItems.Add(new TaskItem { 
                        TaskId = dr.GetInt64(0),
                        Subject = dr.GetString(1),
                        IsComplete = dr.GetBoolean(2),
                    });
                }

                dr.Close();
                TaskItems = taskItems.ToArray();
            }
            finally
            {
                cn.Close();
            }
        }

        public void OnPost(TaskItem item)
        {
            var cn = new SqlConnection();

            var cmd = cn.CreateCommand();
            cmd.CommandText = "INSERT INTO TaskItem(Subject, IsComplete) VALUES(@Subject, @IsComplete)";

            try
            {
                cn.ConnectionString = "Data Source=.;Initial Catalog=ToDoDb;User ID=tododb;Password=123456";
                cn.Open();

                cmd.Parameters.Add(new SqlParameter("Subject", item.Subject));
                cmd.Parameters.Add(new SqlParameter("IsComplete", item.IsComplete));

                cmd.ExecuteNonQuery();
            }
            finally
            {
                cn.Close();
            }

            OnGet();
        }

        public void OnPostWithError(TaskItem item)
        {
            var cn = new SqlConnection();

            var cmd = cn.CreateCommand();
            cmd.CommandText = "INSERT INTO TaskItem(Subject, IsComplete) VALUES(@Subject, @IsComplete)";

            try
            {
                cn.ConnectionString = "Data Source=.;Initial Catalog=ToDoDb;User ID=tododb;Password=123456";
                cn.Open();

                cmd.Parameters.Add(new SqlParameter("Subject", item.Subject));
                cmd.Parameters.Add(new SqlParameter("complete", item.IsComplete));

                cmd.ExecuteNonQuery();
            }
            finally
            {
                cn.Close();
            }

            OnGet();
        }
    }
}

TodoNetCore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TodoNetCore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TodoNetCore/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1 class="display-4">My Tasks</h1>

<form class="form-inline" method="post">
    <div class="form-group">
        <label class="sr-only" for="txtSubject">Subject</label>
        <input type="text" name="Subject" class="form-control" placeholder="Subject" />
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox" name="IsComplte" />
            Is Complete
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
    <button type="submit" class="btn btn-danger" asp-page-handler="WithError">Add with Error</button>
</form>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>TaskId</th>
            <th>Subject</th>
            <th>IsComplete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.TaskItems)
        {
            <tr>
                <td>@item.TaskId</td>
                <td>@item.Subject</td>
                <td>
                    @if (item.IsComplete)
                    {
                        <input type="checkbox" disabled checked />
                    }
                    else
                    {
                        <input type="checkbox" disabled />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

TodoNetCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Todo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2564 - TodoNetCore - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>